version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      API_KEY: ${API_KEY}
      API_SECRET: ${API_SECRET}
      SPRING_DATA_MONGODB_URI: mongodb://db:27017/btc_scheduler
    ports:
      - "8080:8080"
      - "5005:5005"
    depends_on:
      - db
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data: