version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        API_KEY: ${API_KEY}
        API_SECRET: ${API_SECRET}
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://db:27017/btc_scheduler
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data: